# Generated by Django 3.2.6 on 2022-02-17 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('number', models.CharField(max_length=256, verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 2, 17, 18, 36, 14, 543566, tzinfo=utc), verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
