# Generated by Django 3.2.6 on 2022-02-27 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 13, 29, 6, 62134, tzinfo=utc), verbose_name='Время'),
        ),
    ]
