# Generated by Django 3.2.6 on 2022-02-27 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220227_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 17, 19, 41, 960297, tzinfo=utc), verbose_name='Время'),
        ),
    ]
